version: '3.8'

services:
  jupyter:
    build: ./docker/
    restart: always
    volumes:
      - ./notebooks/:/home/jovyan/work
      # - ~/.aws/:/home/jovyan/.aws/
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'