AWSAccountID: '<AWS account id>'
AWSRegion: 'eu-west-1'
Prefix: 'spark-eks'
AdminUserArns:
  - '<ARN of IAM users to be set as administrators>'
AllowedIpRanges: 
  - '<CIDR ranges of allowed public IP addresses>'